server:
  port: 9090

spring:
  application:
    name: APIGATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/order/**
        - id: PaymentService
          uri: lb://PaymentService
          predicates:
            - Path=/payment/**
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/product/**
